version: '3'
services:
  node:
    image: node:14.15.3-alpine
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5431:5432"

  db2:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-db-data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306"


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql-db-data:
